; Cari baris ini dan hilangkan titik koma di depannya
extension_dir = "ext"

; Aktifkan ekstensi yang paling sering dipakai
extension=curl
extension=mbstring
extension=mysqli
extension=openssl
extension=pdo_mysql